Draft: Add EAR diagram
fga-eps-mds/2022-1-MeasureSoftGram-Doc pull request #55
Opened 2022-07-03 19:01 UTC by DanilloGS

closes #38 

**Descrição**
Criar documento de analise de risco

**Tarefas Realizadas**

2022-07-03 19:35 UTC, durvalcarvalho commented
O que é EAR?

2022-07-03 19:53 UTC, DanilloGS commented
@durvalcarvalho, documento parecido com o EAP, que o Hilmer passou, que facilita a levantar possiveis riscos

2022-07-03 21:20 UTC, KiSobral requested changes
O documento ficou muito bom, parabéns!
Entretanto, acredito que o documento realizado não é o mesmo da Planilha de Riscos que é esperada para a matéria.
Sugiro não jogarmos o trabalho fora, mas sim assumi-lo como documento complementar e não fechar a issue #38 , relacionada a planilha de riscos.

2022-07-03 21:20 UTC, KiSobral commented on docs/projeto/analise_de_risco/analise_de_risco.md
> +Para que seja possível uma identificar de forma mais simples os possivéis risco do durante o projeto MeasureSoftGram durante o semestre de 2022/1 foi elaborado o seguinte diagrama.
Ao ler esse tópico, notei alguns erros de português durante o parágrafo. Por isso, deixo uma sugestão de texto:

"Para que seja possível identificar de forma mais simples os possíveis riscos durante o projeto MeasureSoftGram durante o semestre de 2022/1, foi elaborado o diagrama da Estrutura Analítica de Riscos.

A Estrutura Analítica de Riscos (EAR) é uma ferramenta pela qual é possível agrupar os riscos e organizá-ços em categorias. Cada categoria é então dividida em níveis, sendo que cada nível detalha a fonte de riscos para o projeto. Portanto, a EAR é uma estrutura hierárquica de possíveis fontes de risco."

2022-07-03 21:20 UTC, KiSobral commented on docs/projeto/analise_de_risco/analise_de_risco.md
> +Para que seja possível uma identificar de forma mais simples os possivéis risco do durante o projeto MeasureSoftGram durante o semestre de 2022/1 foi elaborado o seguinte diagrama.
Um outro comentário sobre este mesmo parágrafo é que o mesmo deveria estar dentro do tópico da Estrutura Analítica de Riscos.

2022-07-03 21:20 UTC, KiSobral commented on docs/projeto/analise_de_risco/analise_de_risco.md
> +## Estrutura analítica de riscos
É preciso colocar o nome do tópico capitalizado: "Estrutura Analítica de Riscos".

2022-07-03 21:20 UTC, KiSobral commented on docs/projeto/analise_de_risco/analise_de_risco.md
> +- Estimativa: Estimativas que o time fara para cada tarefa durante a sprint.
Correção na acentuação da palavra "fará".

2022-07-03 21:20 UTC, KiSobral commented on docs/projeto/analise_de_risco/analise_de_risco.md
> +# Analise de risco
O documento precisa estar dentro da estrutura de navegação do docsify. É preciso linká-lo à sidebar.

2022-07-12 12:43 UTC, KiSobral requested changes
O documento ficou muito bom! Parabéns! Peço apenas umas mudanças pontuais apontadas nestas reviews para efetuar o merge.

2022-07-12 12:43 UTC, KiSobral commented on docs/documentos/analise_de_risco.md
> +Para que seja possível identificar de forma mais simples os possíveis riscos durante o projeto MeasureSoftGram durante o semestre de 2022/1, foi elaborado o diagrama da Estrutura Analítica de Riscos.
```suggestion
Para que seja possível identificar de forma mais simples os possíveis riscos do projeto MeasureSoftGram durante o semestre de 2022/1, foi elaborado o diagrama da Estrutura Analítica de Riscos.
```

2022-07-12 12:43 UTC, KiSobral commented on docs/documentos/analise_de_risco.md
> +Para interpretar os dados que virão a logo abaixo, na planilha de risco, foi desenvolvida a seguinte matriz.
```suggestion
Para interpretar os dados que virão a seguir, na planilha de risco, foi desenvolvida a seguinte matriz.
```

2022-07-12 12:43 UTC, KiSobral commented on docs/documentos/analise_de_risco.md
> +| R4  | Indisponibilidade do cliente ao decorrer do projeto                                                 | Alto          | Médio   | -         | Sempre que for possível ou necessário, obter o máxi
Aqui, o impacto deste risco no projeto é maior do que médio. Uma classificação adequada seria "alto" ou "muito alto".

2022-07-12 15:17 UTC, merged