Adciona o documento de plano de comunicação
fga-eps-mds/2022-1-MeasureSoftGram-Doc pull request #56
Opened 2022-07-03 19:53 UTC by durvalcarvalho

closes #27 

**Descrição**
Adiciona o documento que descreve a forma como os envolvidos do projeto irão se comunicar.

2022-07-03 21:51 UTC, KiSobral requested changes
O documento ficou realmente muito bom! Só precisam ser realizados pequenos ajustes na grafia do mesmo.

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Este documento visa definir e documentar a forma como a equipe irá se comunicar durante a realização deste projeto. Será definido os canais, as ferramentas, e a forma de comunicação, visando facilita
O parágrafo ficou bom! Precisa somente corrigir a concordância do "Será definido" para "Serão definidos".

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Deste modo, alguns canais de comunicação foram estabelecidos com o objetivo de centralizar a comunicação, permitindo assim que todos os envolvidos possam visaulizar e consultar comunicações já realiz
```suggestion
Deste modo, alguns canais de comunicação foram estabelecidos com o objetivo de centralizar a comunicação, permitindo assim que todos os envolvidos possam visaulizar e consultar comunicações já realizadas. Principal canal de comunicação utilizado é [o canal `measuresoftgram`](https://discord.com/channels/983525905085370368/983525905542565991) da aplicação Discord. Neste canal estão presentes os principais interessados no projeto, como:
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Este documento visa definir e documentar a forma como a equipe irá se comunicar durante a realização deste projeto. Será definido os canais, as ferramentas, e a forma de comunicação, visando facilita
```suggestion
Este documento visa definir e documentar a forma como a equipe irá se comunicar durante a realização deste projeto. Serão definidos os canais, as ferramentas, e a forma de comunicação, visando facilitar o fluxo de trabalho por meio de uma comunicação eficiente e organizada.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +    * Os 10 membros da equipe de desenvolvimento;
A lista não está sendo renderizada corretamente, é preciso adicionar mais espaços para a quebra de linha realmente acontecer no MD.

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +A comunicação neste canal do Discord é realizado principalmente de forma assíncrona, onde os membros enviam as mensagens para o canal e espera o cliente do projeto responder em um tempo oportuno.
```suggestion
A comunicação neste canal do Discord é realizada principalmente de forma assíncrona, em que os membros enviam as mensagens para o canal e esperam o cliente do projeto responder em um tempo oportuno.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Além do canal do Discord, é utilizado a ferramenta Microsoft Teams para realizar videochamadas. Por meio destas chamadas é realizada a comunicação síncrona entre o cliente e a equipe de desenvolvimen
```suggestion
Além do canal do Discord, é utilizada a ferramenta Microsoft Teams para realizar videochamadas. Por meio destas chamadas é realizada a comunicação síncrona entre o cliente e a equipe de desenvolvimento. Normalmente estas chamadas duram entre 1h e 2h, e são agendadas com pelo menos 2 dias de antecedência, sem contar as reuniões recorrentes com horários já definidos em conjunto com o cliente.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Para comunicar entre os membros da equipe de desenvolvimento, além do canal do Discord, é utilizado o aplicativo de mensageria Telegram. Lá existe um grupo onde é discutido horários para a realização
```suggestion
Para comunicar entre os membros da equipe de desenvolvimento, além do canal do Discord, é utilizado o aplicativo de mensageria Telegram. Lá existe um grupo onde são discutidos horários para a realização de reuniões, enquetes para tomada de decisões, e também para discutir o andamento do projeto.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Por mais que exista um grupo no Telegram com somente os membros da equipe de desenvolvimento, ficou definido que as dúvidas e discussões deverão ser feitas no grupo no Discord ou na plataforma de hos
```suggestion
Por mais que exista um grupo no Telegram com somente os membros da equipe de desenvolvimento, ficou definido que as dúvidas e discussões deverão ser feitas no grupo no Discord ou na plataforma de hospedagem de código GitHub. Essa decisão foi feita visando dar visibilidade e transparência a todos os interessados do projeto.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Além das comunicações assíncronas citadas acima, também são realizadas duas reniões semanais de pronto de controle (dailies), com o objetivo de dar visibilidade ao andamento e aos impeditivos das tar
```suggestion
Além das comunicações assíncronas citadas acima, também são realizadas duas reniões semanais de ponto de controle (dailies), com o objetivo de dar visibilidade ao andamento e aos impedimentos das tarefas realizadas durante o andamento das sprints, que possuem o tamanho de uma semana. Estas reuniões são feitas após a aula de Engenharia de Produto de Software, e são planejadas para durarem no máximo 15 minutos. Essas dailies são guiadas pelas 3 seguintes perguntas:
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +    * O que eu já fiz.
Trocar o ponto final "." pelo ponto de interrogação "?" nos itens dessa lista.

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Também é comum a realização de video-chamadas para a comunicação síncrona entre os membros da equipe de desenvolvimento. Geralmente estas reuniões são feitas para tomada de decisão em conjunto e tamb
```suggestion
Também é comum a realização de videochamadas para a comunicação síncrona entre os membros da equipe de desenvolvimento. Geralmente estas reuniões são feitas para tomada de decisão em conjunto e também para discutir as atividades que serão feitas durante a semana, assim como para realizar os ritos do método ágil *scrum* (metodologia adotada no projeto).
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +Uma vez que reuniões tendem a durar mais tempo do que o previsto, e costumam a serem não conclusivas, foi necessário adotar um conjunto de "regras" para tornar as reuniões mais eficientes.
```suggestion
Uma vez que reuniões tendem a durar mais tempo do que o previsto, e costumam ser não conclusivas, foi necessário adotar um conjunto de "regras" para tornar as reuniões mais eficientes.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +* Durante a reunião o "lider" da reunião deve se manter na pauta, e qualquer discursão que não for relacionada ao objetivo da reunião e que estiver demandando tempo excessivo deve ser discutida entre
```suggestion
* Durante a reunião o "líder" da reunião deve se manter na pauta, e qualquer discussão que não for relacionada ao objetivo da reunião e que estiver demandando tempo excessivo deve ser discutida, entre os envolvidos, fora da reunião.
```

2022-07-03 21:51 UTC, KiSobral commented on docs/documentos/plano_de_comunicacao.md
> +* Toda segunda-feira às 19h30 às 21h serão realizadas as reuniões de planejamento.
Os horários precisam ser revisitados e reconfirmados para os passar ao documento.

2022-07-04 18:04 UTC, durvalcarvalho commented
@KiSobral Grato pela revisão! 
Sobre os horários das reuniões fixas, eles já foram definidos?

2022-07-04 18:11 UTC, merged

2022-07-04 19:33 UTC, KiSobral commented
> @KiSobral Grato pela revisão! Sobre os horários das reuniões fixas, eles já foram definidos?

@durvalcarvalho a reunião recorrente com o cliente ocorre a cada segunda-feira as 20h